export function translateToUrdu(text: string): string {
  const dictionary: { [key: string]: string } = {
    "Artificial Intelligence": "مصنوعی ذہانت",
    "transforming": "تبدیل کر رہی ہے",
    "industry": "صنعت",
    "industries": "صنعتیں",
    "healthcare": "صحت کی دیکھ بھال",
    "education": "تعلیم",
    "potential": "صلاحیت",
    "endless": "لامحدود",
    "ethical concerns": "اخلاقی خدشات",
    "must be addressed": "کو حل کرنا ضروری ہے",
    "startup": "نووارد کاروبار",
    "customer": "گاہک",
    "feedback": "رائے",
    "product": "مصنوع",
    "uncertainty": "غیر یقینی",
    "experimentation": "تجربہ کاری",
    "productivity": "پیداواریت",
    "efficiency": "افادیت",
    "multitasking": "کئی کام ایک ساتھ کرنا",
    "mental health": "ذہنی صحت",
    "mindfulness": "ذہنی توجہ",
    "support system": "سپورٹ سسٹم",
    "remote work": "دور دراز سے کام کرنا",
    "flexibility": "لچک",
    "employee": "ملازم",
    "satisfaction": "اطمینان",
    "communication": "ابلاغ",
    "norms": "معیارات",
    "blockchain": "بلاک چین",
    "decentralization": "غیر مرکزیت",
    "supply chain": "سپلائی چین",
    "regulation": "ضابطہ",
    "scalability": "پیمانہ پذیری",
    "habits": "عادات",
    "summary": "خلاصہ",
    "translation": "ترجمہ",
    "growth": "ترقی",
    "technology": "ٹیکنالوجی",
    "improvement": "بہتری",
    "success": "کامیابی",
    "challenge": "چیلنج",
    "solution": "حل",
    "community": "برادری",
    "development": "ترقی",
    "learning": "سیکھنا",
    "opportunity": "موقع",
    "environment": "ماحول",
    "goal": "مقصد",
    "strategy": "حکمت عملی",
    "focus": "توجہ",
    "knowledge": "علم",
    "research": "تحقیق",
    "future": "مستقبل",
    "impact": "اثر",
    "results": "نتائج",
    "ideas": "خیالات",
    "initiative": "پہل",
    "career": "ملازمت",
    "training": "تربیت",
    "team": "ٹیم",
    "plan": "منصوبہ",
    "digital": "ڈیجیٹل",
    "task": "کام",
    "organization": "تنظیم",
    "skills": "مہارتیں",
    "leadership": "رہنمائی",
    "creativity": "تخلیقیت",
    "data": "ڈیٹا",
    "analytics": "تجزیہ",
    "insight": "بصیرت",
    "network": "نیٹ ورک",
    "platform": "پلیٹ فارم",
    "value": "قدر",
    "vision": "نظریہ",
    "mission": "مقصد",
    "objective": "مقصد",
    "resource": "وسیلہ",
    "risk": "خطرہ",
    "time": "وقت",
    "effort": "کوشش",
    "dedication": "عزم",
    "motivation": "حوصلہ افزائی",
    "balance": "توازن",
    "stress": "دباؤ",
    "burnout": "تھکن",
    "feedback loop": "رائے کا چکر",
    "collaboration": "تعاون",
    "process": "عمل",
    "framework": "ڈھانچہ",
    "goal setting": "اہداف کا تعین",
    "remote": "ریموٹ",
    "innovation": "جدت",
    "technology driven": "ٹیکنالوجی سے چلنے والا",
    "automation": "خودکاری",
    "machine learning": "مشین لرننگ",
    "deep learning": "ڈیپ لرننگ",
    "performance": "کارکردگی",
    "culture": "ثقافت",
    "engagement": "شمولیت",
    "user": "صارف",
    "experience": "تجربہ",
     "Books": "کتابیں",
    "Articles": "مضامین",
    "Newsletter": "خبری خط",
    "App": "ایپ",
    "Speaking": "تقریر",
    "Menu": "مینو",
    "Close": "بند کریں",
    "About": "کے بارے میں",
    "The 3-2-1 Newsletter": "تھری ٹو ون خبری خط",
    "The most wisdom per word of any newsletter on the web.": "ویب پر کسی بھی خبری خط کے مقابلے میں فی لفظ سب سے زیادہ حکمت۔",
    "The 3-2-1 Newsletter is one of the most popular newsletters in the world.": "تھری ٹو ون خبری خط دنیا کے سب سے مشہور خبری خطوط میں سے ایک ہے۔",
    "Every Thursday, the latest issue is sent to over 3,000,000 people.": "ہر جمعرات کو تازہ شمارہ 30 لاکھ سے زائد افراد کو بھیجا جاتا ہے۔",
    "Atomic Habits": "ایٹامک ہیبٹس",
  "Atomic Habits Summary": "ایٹامک ہیبٹس کا خلاصہ",
  "Atomic Habits Summary in Three Sentences": "تین جملوں میں ایٹامک ہیبٹس کا خلاصہ",

  "Atomic Habits by James Clear is a comprehensive, practical guide on how to change your habits and get 1% better every day.": 
    "جیمز کلئیر کی ایٹامک ہیبٹس ایک جامع اور عملی رہنما ہے جو یہ سکھاتی ہے کہ اپنی عادات کو کیسے بدلا جائے اور ہر دن 1٪ بہتری کیسے حاصل کی جائے۔",

  "Using a framework called the Four Laws of Behavior Change, Atomic Habits teaches readers a simple set of rules for creating good habits and breaking bad ones.": 
    "بیہیوئر چینج کے چار اصولوں کے فریم ورک کو استعمال کرتے ہوئے، ایٹامک ہیبٹس قارئین کو اچھی عادات بنانے اور بری عادات توڑنے کے لیے سادہ اصول سکھاتی ہے۔",

  "Read the full summary to glean 3 key lessons from Atomic Habits, learn how to build a habit in 4 simple steps, and get a handy reference guide for the strategies recommended throughout the book.": 
    "مکمل خلاصہ پڑھیں تاکہ ایٹامک ہیبٹس سے تین اہم اسباق سیکھیں، چار آسان مراحل میں عادت بنانے کا طریقہ جانیں، اور کتاب میں تجویز کردہ حکمت عملیوں کے لیے ایک آسان ریفرنس گائیڈ حاصل کریں۔"

  };

  let translated = text;
  for (const [en, ur] of Object.entries(dictionary)) {
    translated = translated.replace(new RegExp(en, "gi"), ur);
  }

  return translated;
}
