// lib/scrape.ts

export async function scrapeBlogText(url: string): Promise<string> {
  const dummyContent: Record<string, string> = {
    "https://example.com/ai-future": `
      Artificial Intelligence is transforming every industry...
      From healthcare to education, the potential is endless...
      However, ethical concerns must be addressed responsibly...
    `,
    "https://example.com/startup-success": `
      Launching a startup requires vision, persistence, and market timing...
      Customer feedback is key to iterate your product...
      Founders must embrace uncertainty and rapid experimentation...
    `,
    "https://example.com/productivity-hacks": `
      Productivity isn't about doing more, it's about doing what matters...
      Time blocking and deep work sessions can help you stay focused...
      Avoid multitasking — it's a myth that it increases efficiency...
    `,
    "https://example.com/mental-health-awareness": `
      Mental health is as important as physical health...
      Regular breaks, mindfulness, and support systems matter...
      Let's break the stigma and talk openly about our struggles...
    `,
    "https://example.com/remote-work-future": `
      Remote work is here to stay for many industries...
      Flexibility boosts employee satisfaction and retention...
      But boundaries and communication norms are essential...
    `,
    "https://example.com/blockchain-potential": `
      Blockchain offers trustless transactions and decentralization...
      Beyond crypto, it can revolutionize supply chains and identity verification...
      Regulation and scalability remain key challenges moving forward...
    `
  };

  return (
    dummyContent[url.trim()] ||
    `This is a placeholder blog content for the URL: ${url}. Replace this with actual scraping logic later.`
  )
}
